spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/akshaya_school_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
